FORMAT: 1A
HOST: https://res.uzhenbao.com/v3

# 优真宝数据接口v3

优真宝移动端数据接口

# 文档说明

本文档使用 `RESTful` 风格 API, 当前处于更新期, 在使用过程中如有错误, 及时反馈

# 网络协议

Api使用 `Https` h2协议, 默认端口443

```
https://res.uzhenbao.com/v3
```

# 版本及特性

API 当前版本 `3`,  新版将较之前的版本作更加规范的数据格式及返回消息, 修正前两个版本语义不当的地方

# 请求动作

RESTful API使用如下动词, 完成客户端与服务器间的交互操作

| Method | Description |
|---|---|
| `GET` | 获取单个或列表资源, 正常时返回 `200`, 未找到时返回 `404` |
| `POST` | 创建资源, 正常时返回 `201` |
| `PUT` | 更新一个资源, 成功时返回 `200`|
| `DELETE` | 删除资源, 成功时 `204`|


# HTTP状态码

HTTP状态码是客户端接收服务器响应状态, 根据不同的状态提示用户或处理逻辑, 在接收数据前应首先判断状态码

| Code | Description |
|---|---|
| `200` | Success - *正常或已更新(GET, PUT)*
| `201` | Success - *资源被创建 (POST)*
| `204` | Success - *无返回内容 (DELETE)*
| `400` | Bad Request - *请求验证不通过, 参数有误*
| `401` | Unauthorized - *需要登录验证, 未验证的*
| `403` | Forbidden - *访问被拒绝*
| `404` | Not Found - *资源不存在*
| `405` | Method Not Found - *方法不存在*
| `409` | Conflict - *资源已存在*
| `410` | Gone - *资源已失效, 过期*|
| `412` | Precondition Failed - *不满足请求条件*
| `422` | Unprocessible Entity - *验证错误*
| `429` | Too Many Requests - *请求频繁, 稍后重试*
| `500` | Server Error - *服务器内部错误*
| `503` | Service Unavailable - *服务器繁忙 (30秒内重新尝试请求)*
| `504` | Service Timeout - *请求超时 (30秒内重新尝试请求)*


# 业务状态码

业务状态码会在请求异常时以`application/json`方式返回给客户端, 字段名为`code`, 通常会附带一条`message`和`data`, 部分业务还会添加其它扩展字段，会在相应的请求说明，`request`将返回客户端请求的具体数据，方便开发者进行调试

业务码解释 1 - 2 - 3
* 1 为 http 状态码
* 2 为模块代码
* 3 为业务细分代码

例： 4041303
解释： 未找到用户模块的地址


Response 参数说明

|Name|Type|Description|
|---|---|---|
|status|int|同http状态码|
|code|int|业务状态码|
|message|string|业务消息|
|data|object|与该业务有关的数据|
|request|object|客户端请求数据|

Response 异常示例:
```
{
  "status": 404,
  "code": 4040201,
  "message": "product not found",
  "data": {
    "product_id": "565"
  },
  "request": {
    "url": "https://dev-res.uzhenbao.com/v3/orders/products/preview",
    "method": "POST",
    "data": {
      "items": [
        {
          "amount": "1",
          "product_id": "565",
          "product_item_id": "1037",
          "car_id": "77"
        },
        {
          "amount": "1",
          "product_id": "565",
          "product_item_id": "1038",
          "car_id": "97"
        }
      ],
      "shipping_address_id": "254",
      "is_invoice": "0"
    }
  }
}
```

# 数据类型

接口只返回`Application/json`格式数据, 请不要尝试在`Headers`中使用`Accept`来声明接收的意向数据类型


# 验证

*注意: 以下3种验证结果为全局验证，将不再在具体的接口中描述*

## 1.客户端验证

为了api接口安全,需要接口进行签名验证, 每条请求需要在`Headers`中添加如下参数

| Name | Type | Value | Description |
|---|---|---|---|
|`app-key`| string |`9sk82lsSlw9IKM` |由系统分配, 应用栏目获取 |
|`timestamp`| int |`1478333136` | unix 时间辍, 单位秒 |
|`sign`| string |`60ce041f972501bf2be046fc6d7f5617f8677264` | sha1 混淆获取 |

`sign` 算法: `sha1(httpMethod+apiUrl+timestamp+contentLength+appSecret)`, 注意顺序一致

算法参数说明

| Name | Type | Value | Description |
|---|---|---|---|
|`httpMethod`| string |`GET|POST|PUT|DELETE`| 大写|
|`apiUrl`| string |`https://res.uzhenbao.com/v3/products`| 如有`?|&`参数, 需携带|
|`timestamp`| string |`1478333136` |unix 时间辍, 单位秒, 注意要与header中的`timestamp`值一致|
|`contentLength`| int | `0` | 请求体总长度|
|`appSecret`| string |`ksi28Skxmsw01lZs391` | 由系统分配, 固定, 管理平台`应用`栏目获取, 签名密钥, 不可暴露, 移动端应放在安全的位置,或做包混淆|

验证错误会返回如下几种结果:

```
{
  "status": 504,
  "code": 5040101,
  "message": "not sync timeout",
  "data": null,
  "server_timestamp": 1494297455,
}

```

> 问题原因是客户端与服务器时间不同步导致, 返回的`server_timestamp`为服务器当前时间, 移动端应计算时差以保证时间同步,
后再次重试请求, 如请求失败最多尝试5次, 均失败后停止请求并告知用户: 稍后重试

```
{
  "status": 401,
  "code": 4012502,
  "message": "sign unauthorized",
  "data": null
}
```

> 签名错误, 请确认参数及顺序正确, 核对sha1方法是否有差异


```
{
  "status": 409,
  "code": 4090003,
  "message": "request repeat",
  "data": null
}
```

> 同一时间内避免重复提交相同内容, 间隔时间为1秒

```
{
  "status": 404,
  "code": 4042502,
  "message": "app key not found",
  "data": null
}
```

> app key 不存在，检查移动app key是否正确


## 2.请求参数验证

为了保证客户端输入的数据为有效数据，服务器将验证每个接口所需要的特定的参数所支持的数据类型及数据长度等信息

验证错误会返回与当前请求相关的错误信息

```
{
  "status": 400,
  "code": 4000001,
  "message": "params error",
  "data": {
    "items": [
      "The items field is required."
    ]
  },
  "request": {
    "url": "https://dev-res.uzhenbao.com/v3/orders/products/preview",
    "method": "POST",
    "data": []
  }
}
```

> 检查对应接口的参数是否按要求包含的请求体中


## 3.用户身份验证

需要验证用户身份地方使用`Token`机制验证用户身份, 用户请求接口中使用`Headers`将`user-id`和`access-token`提交给服务器验证

例：

```
{
    user-id: 1,
    access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux
}
```

| Name | Value | Description |
|---|---|---|
|`user-id`| `22` | 用户id |
|`access-token`| `$2y$10$Kbz6jSCLHLkm4D5Gp67xhux` | 用户访问token |


验证错误将会返回如下结果：

```
{
  "status": 401,
  "code": 4011301,
  "message": "user unauthorized",
  "data": null
}
```

> 用户验证失败, token或已过期, 应执行重新登录操作


# H5单页

以下页面在合适的位置添加链接或加载至webview

| Description | Url |
|---|---|
| 平台服务协议 | `https://m.uzhenbao.com/users/agreement` |
| 商品售后服务协议 | `https://m.uzhenbao.com/goodsReturns/agreement` |
| 销售者说明 | `https://m.uzhenbao.com/orderResults/agreement` |
| 找回密码 | `https://m.uzhenbao.com/findPassword` |
| 应用官网 | `https://app.uzhenbao.com` |




# group 用户

## 设置 [/userSettings/autoReply]

### 显示自动回复内容 [GET /userSettings/autoReply]

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

+ Response 200 (application/json)


            {
              "user_id": 2300,
              "is_message_auto_reply": 1,
              "auto_reply_content": "你好我现在不在",
              "created_at": "2017-05-09 13:22:49",
              "updated_at": "2017-05-09 13:23:53"
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040001,
              "message": "not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/userSettings/autoReply",
                "method": "GET",
                "data": []
              }
            }

### 设置并打开自动回复 [POST /userSettings/autoReply/open]


Request 参数

| Name | Type | Length | Value | Description |
|---|---|---|---|---|
|`auto_reply_content`|string|(0,255]|你好，我现在有事不在，稍后联系你|设置自动回复的消息|

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

    + Attributes

        + auto_reply_content: 你好，我现在有事不在，稍后联系你 (required) - 回复内容

+ Response 201 (application/json)

            {
              "user_id": 2300,
              "updated_at": "2017-05-09 16:03:27",
              "created_at": "2017-05-09 16:03:27",
              "auto_reply_content": "你好我现在不在",
              "is_message_auto_reply": 1
            }

### 关闭自动回复 [PUT /userSettings/autoReply/close]


+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux


+ Response 200 (application/json)

            {
              "user_id": 2300,
              "is_message_auto_reply": 0,
              "auto_reply_content": "你好我现在不在",
              "created_at": "2017-05-09 16:03:27",
              "updated_at": "2017-05-09 16:11:29"
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040001,
              "message": "not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/userSettings/autoReply",
                "method": "GET",
                "data": []
              }
            }

## 订单 [/trades]

状态说明

|Name|Value|Description|
|---|---|---|
|`trade.state`|0|正常订单|
|`trade.state`|1|已完成订单|
|`trade.state`|-1|已关闭订单|
|`trade.payment.state`|0|未付款|
|`trade.payment.state`|1|已付款|
|`trade.payment.state`|-1|已过期|
|`trade.route.state`|0|未发货|
|`trade.route.state`|1|已发货|
|`trade.route.state`|2|已收货|



### 所有订单 [GET /trades]


可选 `status` 业务状态进行筛选

> 例: /trades?status=waitPay

|Name|Value|Description|
|---|---|---|
|`status`|`waitPay`| 待付款 |
|`status`|`inProcess`|进行中|
|`status`|`finished`|已完成|
|`status`|`closed`|已关闭|


+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

+ Response 200 (application/json)

            {
              "total": 1,
              "per_page": 15,
              "current_page": 1,
              "last_page": 1,
              "next_page_url": null,
              "prev_page_url": null,
              "from": 1,
              "to": 1,
              "data": [
                {
                  "trade_no": "17051111521223080667",
                  "user_id": 2300,
                  "number": 2,
                  "original_price": "0.04",
                  "preferential_price": null,
                  "total_price": "0.00",
                  "type": 0,
                  "state": 0,
                  "coupon_id": null,
                  "user_coupon_id": null,
                  "is_invoice": 0,
                  "created_at": "2017-05-11 11:52:12",
                  "updated_at": "2017-05-11 11:52:12",
                  "deleted_at": null,
                  "closed_at": null,
                  "opened_at": "2017-05-11 11:52:12",
                  "finished_at": null,
                  "items": [
                    {
                      "item_no": "1231231231",
                      "user_id": 2300,
                      "merchant_id": null,
                      "seller_id": null,
                      "buyer_id": null,
                      "product_id": 565,
                      "product_item_id": 1037,
                      "procurement_id": null,
                      "user_product_id": null,
                      "number": 1,
                      "unit_price": "0.02",
                      "total_price": "0.02",
                      "is_support_return": null,
                      "return_expired_at": null,
                      "is_returned": null,
                      "returned_at": null,
                      "is_refunded": null,
                      "refunded_at": null,
                      "created_at": null,
                      "updated_at": null,
                      "product": {
                        "id": 565,
                        "category_id": 1,
                        "category_child_id": 1,
                        "admin_id": 1,
                        "title": "测试1元测试",
                        "keywords": "",
                        "description": "规则：巴拉巴拉",
                        "price": "1.00",
                        "reference_price": "200.00",
                        "likes": 0,
                        "sales": 0,
                        "comments": 0,
                        "views": 16,
                        "favorites": 0,
                        "product_no": "",
                        "rebate": "0.00",
                        "title_image": "http://dev-api.uzhenbao.com/libraries/images/products/20170505113138844772.jpg",
                        "postage": "0.00",
                        "stock": 10,
                        "sort": 1,
                        "type": 0,
                        "status": 1,
                        "created_at": "2017-05-05 11:43:40",
                        "updated_at": "2017-05-11 11:28:34",
                        "flash_buy_id": 0,
                        "group_buy_id": 0,
                        "group_buy_preferential_price": "0.00",
                        "merchant_id": 0,
                        "is_audited": null,
                        "sizes": "[\"\\u6b63\\u5e38\"]",
                        "colors": "[\"\\u767d\\u8272\"]",
                        "brands": null,
                        "models": null,
                        "styles": null,
                        "genders": null,
                        "textures": null,
                        "week_return": 0,
                        "week_exchange": null,
                        "name": "收纳盒"
                      },
                      "product_item": {
                        "id": 1037,
                        "product_id": 565,
                        "color": "红色",
                        "size": "xl",
                        "price": "0.02",
                        "image": "https://dev-api.uzhenbao.com/uploads/products/20170502093339176526.jpg",
                        "stock": 1212,
                        "updated_at": "2017-05-11 11:52:12",
                        "created_at": "2017-04-18 17:39:13"
                      },
                      "user_product": null,
                      "procurement": null
                    },
                    {
                      "item_no": "1231231231",
                      "user_id": 2300,
                      "merchant_id": null,
                      "seller_id": null,
                      "buyer_id": null,
                      "product_id": 565,
                      "product_item_id": 1038,
                      "procurement_id": null,
                      "user_product_id": null,
                      "number": 1,
                      "unit_price": "0.02",
                      "total_price": "0.02",
                      "is_support_return": null,
                      "return_expired_at": null,
                      "is_returned": null,
                      "returned_at": null,
                      "is_refunded": null,
                      "refunded_at": null,
                      "created_at": null,
                      "updated_at": null,
                      "product": {
                        "id": 565,
                        "category_id": 1,
                        "category_child_id": 1,
                        "admin_id": 1,
                        "title": "测试1元测试",
                        "keywords": "",
                        "description": "规则：巴拉巴拉",
                        "price": "1.00",
                        "reference_price": "200.00",
                        "likes": 0,
                        "sales": 0,
                        "comments": 0,
                        "views": 16,
                        "favorites": 0,
                        "product_no": "",
                        "rebate": "0.00",
                        "title_image": "http://dev-api.uzhenbao.com/libraries/images/products/20170505113138844772.jpg",
                        "postage": "0.00",
                        "stock": 10,
                        "sort": 1,
                        "type": 0,
                        "status": 1,
                        "created_at": "2017-05-05 11:43:40",
                        "updated_at": "2017-05-11 11:28:34",
                        "flash_buy_id": 0,
                        "group_buy_id": 0,
                        "group_buy_preferential_price": "0.00",
                        "merchant_id": 0,
                        "is_audited": null,
                        "sizes": "[\"\\u6b63\\u5e38\"]",
                        "colors": "[\"\\u767d\\u8272\"]",
                        "brands": null,
                        "models": null,
                        "styles": null,
                        "genders": null,
                        "textures": null,
                        "week_return": 0,
                        "week_exchange": null,
                        "name": "收纳盒"
                      },
                      "product_item": {
                        "id": 1038,
                        "product_id": 565,
                        "color": "白色",
                        "size": "xl",
                        "price": "0.02",
                        "image": "https://dev-api.uzhenbao.com/libraries/images/products/20170418173901936797.png",
                        "stock": 1203,
                        "updated_at": "2017-05-11 11:52:12",
                        "created_at": "2017-04-18 17:39:13"
                      },
                      "user_product": null,
                      "procurement": null
                    }
                  ]
                }
              ]
            }


### 查看订单 [GET /trades/{tradeNo}]

+ Parameters

    + tradeNo: 17051111521223080667 -  trade No

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

+ Response 200 (application/json)

            {
              "trade_no": "17051111521223080667",
              "user_id": 2300,
              "number": 2,
              "original_price": "0.04",
              "preferential_price": null,
              "total_price": "0.00",
              "type": 0,
              "state": 0,
              "coupon_id": null,
              "user_coupon_id": null,
              "is_invoice": 0,
              "created_at": "2017-05-11 11:52:12",
              "updated_at": "2017-05-11 11:52:12",
              "deleted_at": null,
              "closed_at": null,
              "opened_at": "2017-05-11 11:52:12",
              "finished_at": null,
              "route": null,
              "payment": {
                "state": 0,
                "alipay_no": null,
                "wechat_no": null,
                "paid_at": null,
                "expired_at": "2017-05-11 12:07:12",
                "created_at": "2017-05-11 11:52:12",
                "updated_at": "2017-05-11 11:52:12"
              },
              "address": {
                "comment": null,
                "province": "北京",
                "city": "北京市",
                "area": "东城区",
                "detail": "12321321",
                "phone": "18017695652",
                "name": "123213",
                "created_at": "2017-05-11 11:52:12",
                "updated_at": "2017-05-11 11:52:12"
              },
              "items": [
                {
                  "item_no": "1231231231",
                  "user_id": 2300,
                  "merchant_id": null,
                  "seller_id": null,
                  "buyer_id": null,
                  "product_id": 565,
                  "product_item_id": 1037,
                  "procurement_id": null,
                  "user_product_id": null,
                  "number": 1,
                  "unit_price": "0.02",
                  "total_price": "0.02",
                  "is_support_return": null,
                  "return_expired_at": null,
                  "is_returned": null,
                  "returned_at": null,
                  "is_refunded": null,
                  "refunded_at": null,
                  "created_at": null,
                  "updated_at": null
                },
                {
                  "item_no": "1231231231",
                  "user_id": 2300,
                  "merchant_id": null,
                  "seller_id": null,
                  "buyer_id": null,
                  "product_id": 565,
                  "product_item_id": 1038,
                  "procurement_id": null,
                  "user_product_id": null,
                  "number": 1,
                  "unit_price": "0.02",
                  "total_price": "0.02",
                  "is_support_return": null,
                  "return_expired_at": null,
                  "is_returned": null,
                  "returned_at": null,
                  "is_refunded": null,
                  "refunded_at": null,
                  "created_at": null,
                  "updated_at": null
                }
              ],
              "comment": null
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040001,
              "message": "not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667",
                "method": "GET",
                "data": []
              }
            }


# group 平台商品

## 购买 [/trades]


购买商品APP执行流程: 

* `预览订单` -> `生成订单` -> `订单金额 > 0` ->  `选择支付方式获取平台交易信息` -> `客户端向第三方支付发起交易` ->
`第三方支付返回结果` -> `完成`

* `预览订单` -> `生成订单` -> `订单金额 = 0` ->  `确认免费` -> `完成` 


### 预览订单 [POST /trades/preview]

生成订单前使用此接口确认库存, 优惠及价格信息, 是否可使用优惠券等

Request 参数

|Name|Type|Reqruied|Value|Length|Description|
|---|---|---|---|---|---|
|`items`|array|required||N|商品数组|
|`items.*`|object|required||N|对象|
|`items.*.product_id`|int|required|2|N|商品id|
|`items.*.product_item_id`|int|required|23|N|商品sku id|
|`items.*.number`|int|required|1|[1,99]|该商品购买数量|
|`items.*.car_id`|int|optional|3|N|购物车id, 生成订单后将删除对应的购物车内商品|
|`shipping_address_id`|int|optional|12|N|用户收货地址id|
|`is_invoice`|int|optional|1|N|`1|0` 开具发票, 1 需要, 0 不需要|
|`coupon_id`|int|optional|2|N|优惠券id|
|`comment`|string|optional|尽早发货|[0, 255]|备注内容|

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

    + Attributes

        + items (array, required)
            + (object)
                + product_id: 2 (required) - id of a product
                + product_item_id: 23 (required) - id of a product sku
                + number: 1 (required) - number of product sku
                + car_id: 2 (optional) - shopping car id
            + (object)
                + product_id: 2 (required) - id of a product
                + product_item_id: 23 (required) - id of a product sku
                + number: 1 (required) - number of product sku
                + car_id: 3 (optional) - shopping car id
        + shipping_address_id: 4 (optional) - 收货地址id
        + is_invoice: 0 (optional, number) - 默认0 不开具发票, 1 开发票
        + coupon_id: 1 (optional, number) - 优惠券id
        + comment: 这是备注内容 (optional, string) - 备注内容, 最多255字

+ Response 200 (application/json)

            {
              "total_price": 2,
              "original_price": 2,
              "postage": 0,
              "coupon_price": 0,
              "available_coupons": [
                {
                  "id": 16,
                  "coupon_id": 43,
                  "coupon_code_id": 93,
                  "user_id": 2300,
                  "created_at": "2017-03-28 18:45:06",
                  "updated_at": "2017-05-04 14:35:01",
                  "is_used": 0,
                  "expired_at": "2017-07-30 00:00:00",
                  "coupon": {
                    "id": 43,
                    "name": "111",
                    "amount": 111,
                    "allowance": 108,
                    "cash": "11.00",
                    "overflow_price": "0.00",
                    "created_at": "2017-03-28 17:06:26",
                    "updated_at": "2017-05-04 16:08:04",
                    "expired_at": "2017-07-30 00:00:00",
                    "deleted_at": null,
                    "issue_id": 1,
                    "start_at": "2017-02-28 00:00:00",
                    "end_at": "2017-07-28 00:00:00",
                    "category_id": 0,
                    "category": null
                  }
                }
              ]
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040201,
              "message": "product not found",
              "data": {
                "product_id": "565"
              },
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0"
                }
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040202,
              "message": "product item not found",
              "data": {
                "product_item_id": "10371"
              },
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "1",
                      "product_id": "564",
                      "product_item_id": "10371",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0"
                }
              }
            }


+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4033101,
              "message": "coupon not available",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "99",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0",
                  "coupon_id": "19"
                }
              }
            }



### 生成订单 [POST /trades]


Request 参数

|Name|Type|Reqruied|Value|Length|Description|
|---|---|---|---|---|---|
|`items`|array|required||N|商品数组|
|`items.*`|object|required||N|对象|
|`items.*.product_id`|int|required|2|N|商品id|
|`items.*.product_item_id`|int|required|23|N|商品sku id|
|`items.*.number`|int|required|1|[1,99]|该商品购买数量|
|`items.*.car_id`|int|optional|3|N|购物车id, 生成订单后将删除对应的购物车内商品|
|`shipping_address_id`|int|required|12|N|用户收货地址id|
|`is_invoice`|int|optional|1|N|`1|0` 开具发票, 1 需要, 0 不需要|
|`coupon_id`|int|optional|2|N|优惠券id|
|`comment`|string|optional|尽早发货|[0, 255]|备注内容|


+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

    + Attributes

        + items (array, required)
            + (object)
                + product_id: 2 (required) - id of a product
                + product_item_id: 23 (required) - id of a product sku
                + number: 1 (required) - number of product sku
                + car_id: 2 (optional) - shopping car id
            + (object)
                + product_id: 2 (required) - id of a product
                + product_item_id: 23 (required) - id of a product sku
                + number: 1 (required) - number of product sku
                + car_id: 3 (optional) - shopping car id
        + shipping_address_id: 4 (required) - 收货地址id
        + is_invoice: 0 (optional, number) - 默认0 不开具发票, 1 开发票
        + coupon_id: 1 (optional, number) - 优惠券id
        + comment: 这是备注内容 (optional, string) - 备注内容, 最多255字


+ Response 201 (application/json)

            {
              "trade_no": "17051111521223080667",
              "user_id": 2300,
              "number": 2,
              "total_price": 0,
              "original_price": 0.04,
              "is_invoice": 0,
              "type": 0,
              "state": 0,
              "updated_at": "2017-05-11 11:52:12",
              "created_at": "2017-05-11 11:52:12",
              "opened_at": "2017-05-11 11:52:12",
              "payment": {
                "state": 0,
                "expired_at": "2017-05-11 12:07:12",
                "updated_at": "2017-05-11 11:52:12",
                "created_at": "2017-05-11 11:52:12"
              },
              "address": {
                "province": "北京",
                "city": "北京市",
                "area": "东城区",
                "detail": "12321321",
                "phone": "18017695652",
                "name": "123213",
                "comment": null,
                "updated_at": "2017-05-11 11:52:12",
                "created_at": "2017-05-11 11:52:12"
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040201,
              "message": "product not found",
              "data": {
                "product_id": "565"
              },
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0"
                }
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040202,
              "message": "product item not found",
              "data": {
                "product_item_id": "10371"
              },
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "1",
                      "product_id": "564",
                      "product_item_id": "10371",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0"
                }
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4041303,
              "message": "address not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254555",
                  "coupon_id": "16",
                  "is_invoice": "0"
                }
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4033101,
              "message": "coupon not available",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product/preview",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "99",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0",
                  "coupon_id": "19"
                }
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4030202,
              "message": "product item under stocks",
              "data": {
                "product_item_id": "1037"
              },
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/orders/product",
                "method": "POST",
                "data": {
                  "items": [
                    {
                      "amount": "99",
                      "product_id": "565",
                      "product_item_id": "1037",
                      "car_id": "77"
                    },
                    {
                      "amount": "1",
                      "product_id": "565",
                      "product_item_id": "1038",
                      "car_id": "97"
                    }
                  ],
                  "shipping_address_id": "254",
                  "is_invoice": "0"
                }
              }
            }



### 支付宝支付 [GET /trades/{tradeNo}/alipay]

+ Parameters

    + tradeNo: 17051111521223080667 -  trade No

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux


+ Response 200 (application/json)

            {
              "payment": "alipay",
              "string": "alipay_sdk=lokielse%2Fomnipay-alipay&app_id=2016101802222984&biz_content=%7B%22subject%22%3A%22%5Cu4f18%5Cu771f%5Cu5b9d%5Cu8ba2%5Cu5355%5B17051111521223080667%5D%22%2C%22out_trade_no%22%3A%2217051111521223080667%22%2C%22total_amount%22%3A%220.01%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%7D&charset=UTF-8&format=JSON&method=alipay.trade.app.pay&notify_url=http%3A%2F%2Fdev-api.uzhenbao.com%2Falipay%2Fnotify&sign_type=RSA&timestamp=2017-05-11+17%3A27%3A56&version=1.0&sign=aMAVRwnTVpDKFeWo5%2BtdZG5Dz%2FXljw%2Bj963JdrEJGhssh9h1XSrWE4f%2BqdqjoFbRVsz5UaOh1Hl%2Bie2HPiG5%2Fr8EuC%2FHQNhShuozVwS1vyJh0iRHjmp%2BZ00cJqKwB27O1dQCSwJzU7FhHzOKeQJn%2FzABgj5RSQjTvWuUGBOwFe0%3D"
            }

+ Response 409 (application/json)

            {
              "status": 409,
              "code": 4099801,
              "message": "payment existed",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4030504,
              "message": "trade closed",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4039803,
              "message": "payment expired",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040501,
              "message": "trade not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/170511115212230806617/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 500 (application/json)

            {
              "status": 500,
              "code": 5000001,
              "message": "unknown error",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

### 微信支付 [GET /trades/{tradeNo}/wechat]

+ Parameters

    + tradeNo: 17051111521223080667 -  trade No

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux

+ Response 200 (application/json)

            {
              "payment": "wechat",
              "data": {
                "appid": "wxf4110050c5a73bf4",
                "partnerid": "1414572802",
                "prepayid": "wx20170511173425d75426626f0842712168",
                "noncestr": "8fd42604ccd5a9de10942c06bcc9f0b0",
                "timestamp": 1494495258,
                "sign": "FDA41330C5726B50666C6883602DE033",
                "packagevalue": "Sign=WXPay"
              }
            }

+ Response 409 (application/json)

            {
              "status": 409,
              "code": 4099801,
              "message": "payment existed",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4030504,
              "message": "trade closed",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4039803,
              "message": "payment expired",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 404 (application/json)

            {
              "status": 404,
              "code": 4040501,
              "message": "trade not found",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/170511115212230806617/alipay",
                "method": "GET",
                "data": []
              }
            }

+ Response 500 (application/json)

            {
              "status": 500,
              "code": 5000001,
              "message": "unknown error",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/alipay",
                "method": "GET",
                "data": []
              }
            }


### 确认免费 [GET /trades/{tradeNo}/confirmFree]

+ Parameters

    + tradeNo: 17051111521223080667 -  trade No

+ Request

    + Headers

            timestamp: 1478840722
            app-key: 92lsk20ks
            sign: 9cf1587dac6bef69d34eaaec467689a7ffe2a5d5
            user-id: 2300
            access-token: $2y$10$Kbz6jSCLHLkm4D5Gp67xhux


+ Response 200 (application/json)

            {
              "trade_no": "17051111521223080667",
              "user_id": 2300,
              "number": 2,
              "original_price": "0.04",
              "preferential_price": null,
              "total_price": "0.00",
              "type": 0,
              "state": 0,
              "coupon_id": null,
              "user_coupon_id": null,
              "is_invoice": 0,
              "created_at": "2017-05-11 11:52:12",
              "updated_at": "2017-05-11 11:52:12",
              "deleted_at": null,
              "closed_at": null,
              "opened_at": "2017-05-11 11:52:12",
              "finished_at": null,
              "route": null,
              "payment": {
                "state": 1,
                "amount": 0,
                "alipay_no": null,
                "wechat_no": null,
                "paid_at": "2017-05-11 18:48:21",
                "expired_at": null,
                "created_at": "2017-05-11 11:52:12",
                "updated_at": "2017-05-11 18:48:21"
              },
              "address": {
                "comment": null,
                "province": "北京",
                "city": "北京市",
                "area": "东城区",
                "detail": "12321321",
                "phone": "18017695652",
                "name": "123213",
                "created_at": "2017-05-11 11:52:12",
                "updated_at": "2017-05-11 11:52:12"
              },
              "items": [
                {
                  "item_no": "1231231231",
                  "user_id": 2300,
                  "merchant_id": null,
                  "seller_id": null,
                  "buyer_id": null,
                  "product_id": 565,
                  "product_item_id": 1037,
                  "procurement_id": null,
                  "user_product_id": null,
                  "number": 1,
                  "unit_price": "0.02",
                  "total_price": "0.02",
                  "is_support_return": null,
                  "return_expired_at": null,
                  "is_returned": null,
                  "returned_at": null,
                  "is_refunded": null,
                  "refunded_at": null,
                  "created_at": null,
                  "updated_at": null
                },
                {
                  "item_no": "1231231231",
                  "user_id": 2300,
                  "merchant_id": null,
                  "seller_id": null,
                  "buyer_id": null,
                  "product_id": 565,
                  "product_item_id": 1038,
                  "procurement_id": null,
                  "user_product_id": null,
                  "number": 1,
                  "unit_price": "0.02",
                  "total_price": "0.02",
                  "is_support_return": null,
                  "return_expired_at": null,
                  "is_returned": null,
                  "returned_at": null,
                  "is_refunded": null,
                  "refunded_at": null,
                  "created_at": null,
                  "updated_at": null
                }
              ],
              "comment": null
            }

+ Response 403 (application/json)

            {
              "status": 403,
              "code": 4030003,
              "message": "forbidden",
              "data": null,
              "request": {
                "url": "https://dev-res.uzhenbao.com/v3/trades/17051111521223080667/confirmFree",
                "method": "GET",
                "data": []
              }
            }
